---
title: 'DE Analysis: Pairwise Brain Regions'
author: "Emma Jones"
date: "2023-05-22"
output: html_document
---

#### Load in Packages

```{r load in packages}
suppressPackageStartupMessages({
  library(tidyverse)
  library(DESeq2)
  library(styler)
  library(lintr)
  library(here)
  })
```


```{r read in data}
load(here("data", "cpm_out", "cpm_counts_metadata.RData"))

# read in gene counts data
gene_counts <- read.table(
  here("data", "nextflow", "bambu", "counts_gene.txt"),
  header = TRUE
)

# rename columns
colnames(gene_counts) <- str_extract(colnames(gene_counts), "sample..")
```

### Run DESeq2

First I need to make the DESeq DataSet object

```{r prep data for deseq2}
dds <- DESeqDataSetFromMatrix(countData = round(gene_counts),
                              colData = sample_collection_metadata,
                              design = ~ sex + tissue)
nrow(dds)

keep <- rowSums(counts(dds)) > 1
dds <- dds[keep,]
nrow(dds)

#vst normalization
vsd <- vst(dds, blind = FALSE)
head(assay(vsd), 3)

colData(vsd)

plotPCA(vsd, intgroup = c("sex", "tissue"))

plotPCA(vsd, intgroup = c("tissue"))

plotPCA(vsd, intgroup = c("med_len"))

plotPCA(vsd, intgroup = c("RIN"))
```

Next, I can run DESeq2. I don't think I need to include anything other than tissue and sex based on these plots. I'm leaving sex because I'm interested in it, thought I know it may not have a lot of sig differences.

```{r run DESeq2}
dds <- estimateSizeFactors(dds)
dds <- estimateDispersions(dds)
dds <- nbinomWaldTest(dds, maxit = 5000) # the more I increase this
# the less "did not converge" columns you will get

get_de_results <- function(tissue1, tissue2){
  
  temp_results <- results(dds, contrast = c("tissue", tissue1, tissue2),
                          independentFiltering = TRUE, alpha = 0.05,
                          pAdjustMethod = "BH", parallel = TRUE)
  saveRDS(temp_results, here("data", "deseq2_data", paste0(tissue1, "_",
                                                           tissue2,
                                                           "_results.Rds")
                             )
          )
  assign(paste0(tissue1, "_", tissue2,"_res"), temp_results, env = .GlobalEnv)
}

```



Run function for saving data

```{r get de results}

get_de_results("cerebellum", "cortex")
get_de_results("cerebellum", "hippocampus")
get_de_results("cerebellum", "striatum")
get_de_results("cortex", "hippocampus")
get_de_results("cortex", "striatum")
get_de_results("striatum", "hippocampus")

```






